### ISSUE TITLE
Only works on Overlay Canvases

### ISSUE THREAD

**Issue by rotolonico** [brogan89/MinMaxSlider#2]
I have been struggling to make the slider work for any type of canvas other than the overlay one. The click would just not register and the maxSlider would just bump up to its maximum value.

**Comment by brogan89** [comment]
That will be because its using world positions not screen space positions. There will need to be some conversions from world space to camera space. I didn't initially do that because I was a bit lazy, sorry, and it wasn't required for the game I'm working on. Which is where the code comes from.

I am not sure when I will find the time to dig into it though sorry, currently trying to release a game. But will add that support as soon as I can. If you beat me to it, please do PR I would really appreciate contribution.

Thanks

**Comment by rotolonico** [comment]
I believe I have fixed it, merge when you can
